name: Deployment - Prod

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Run Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }} 
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/${{ secrets.SSH_FOLDER }}
            git reset --hard
            git checkout main
            git pull
            go run bin/extend.go
            cd storefront
            go run bin/lang.go
            npm i
            npm run build
            cd ..
            docker compose stop
            docker compose up -d
